name: crypted_preferences
description: Flutter preferences management with crypto capabilities
version: 1.0.0
homepage: https://github.com/jaumard/crypted_preferences
repository: https://github.com/jaumard/crypted_preferences
author: jaumard <jimmy.aumard@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:


dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
